version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "4000:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:4000/
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/.n8n/workflows
    networks:
      - n8n-network

  chat-app:
    build: ./chat-app
    container_name: chat-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - LLM_HOST=host.docker.internal
      - LLM_PORT=11434
    volumes:
      - chat_data:/app/data
    networks:
      - n8n-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  n8n_data:
  chat_data:

networks:
  n8n-network:
    driver: bridge
